services:
  
  app:
    image: aws_class
    build: .

    environment:
      AWS_ACCESS_KEY: ${AWS_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION}
      AWS_SECRET_KEY: ${AWS_SECRET_KEY}
      S3_BUCKET: ${S3_BUCKET}
      # API_URL: ${API_URL}

